author:
  name: sgd
  url: https://github.com/sgdxbc

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      title: ""
      excerpt_separator: <!-- more -->

baseurl: "/ideas"
include:
  - _pages

remote_theme: sgdxbc/tale

permalink:    /:year-:month-:day/:title
paginate:     20

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
