name: Build and Deploy

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo run

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/web/ideas # The folder the action should deploy.
